// NOTIFICATION
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

// AUTH
export const SET_LOADING = "SET_LOADING";
export const CLEAR_INPUTS = "CLEAR_INPUTS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const EMAIL_ERROR = "EMAIL_ERROR";
export const PASSWORD_ERROR = "PASSWORD_ERROR";
export const SET_USER = "SET_USER";
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_ACCOUNT = "SET_ACCOUNT";

// USER PORTFOLIOS
export const LOADING_PORTFOLIOS = "LOADING_PORTFOLIOS";
export const ADD_PORTFOLIO = "ADD_PORTFOLIO";
export const EDIT_PORTFOLIO = "EDIT_PORTFOLIO";
export const SET_PORTFOLIOS = "SET_PORTFOLIOS";
export const REMOVE_PORTFOLIO = "REMOVE_PORTFOLIO";
export const SET_ACTIVE_PORTFOLIO = "SET_ACTIVE_PORTFOLIO";


// PORTFOLIOS STOCKS
export const LOADING_PORTFOLIO_STOCKS = "LOADING_PORTFOLIO_STOCKS ";
export const ADD_PORTFOLIO_STOCK = "ADD_PORTFOLIO_STOCK";
export const GET_PORTFOLIO_STOCKS = "GET_PORTFOLIO_STOCKS";
export const REMOVE_PORTFOLIO_STOCK = "REMOVE_PORTFOLIO_STOCK";

// PORTFOLIOS TRACKED STOCKS
export const LOADING_PORTFOLIO_TRACKED_STOCKS = "LOADING_PORTFOLIO_TRACKED_STOCKS";
export const ADD_PORTFOLIO_TRACKED_STOCK = "ADD_PORTFOLIO_TRACKED_STOCK";
export const GET_PORTFOLIO_TRACKED_STOCKS = "GET_PORTFOLIO_TRACKED_STOCKS";
export const REMOVE_PORTFOLIO_TRACKED_STOCK = "REMOVE_PORTFOLIO_TRACKED_STOCK";

